## Autostart always
exec_always --no-startup-id kanshictl reload

## Autostart once
exec --no-startup-id kanshi
exec --no-startup-id waybar
exec --no-startup-id swayidle
exec --no-startup-id playerctld daemon
exec --no-startup-id fcitx5

exec --no-startup-id blueman-applet
exec --no-startup-id nm-applet
exec --no-startup-id gammastep-indicator -P

exec --no-startup-id "${XDG_DATA_HOME}/desktop/autostart"

# App binding
bindcode --no-repeat $mod+$return exec --no-startup-id "${TERMINAL}"
bindcode --no-repeat $mod+$d exec --no-startup-id "dmenu_path | wmenu -i | xargs swaymsg exec --"
bindcode --no-repeat $mod+$w exec --no-startup-id "${BROWSER}"
bindcode --no-repeat $print exec --no-startup-id "XDG_CURRENT_DESKTOP=sway ${SCREENSHOT}"
bindcode --no-repeat $mod+$p exec --no-startup-id "${PDFREADER}"
bindcode --no-repeat $mod+$m exec --no-startup-id "${EMAIL}"
bindcode --no-repeat $mod+$n exec --no-startup-id "${RSSFEED}"
bindcode --no-repeat $mod+$e exec --no-startup-id "${FILEMANAGER}"
bindcode --no-repeat $mod+Shift+$w exec --no-startup-id "${PRIVATE_BROWSER}"
bindcode --no-repeat $mod+Shift+$v exec --no-startup-id pavucontrol
bindcode --no-repeat $mod+Shift+$b exec --no-startup-id blueman-manager
bindcode --no-repeat $mod+Shift+$d exec --no-startup-id dmenu-options
bindcode --no-repeat $mod+$s [app_id="terminal_scratchpad"] scratchpad show; \
																			exec --no-startup-id sh -c "pgrep -xf '${TERMINAL_SCRATCHPAD}' || ${TERMINAL_SCRATCHPAD}"
