# Toggle sticky window
bindcode --no-repeat $mod+Shift+$s sticky toggle

# Navigation
bindcode $mod+$j focus left
bindcode $mod+$k focus right
bindcode $mod+$l focus up
bindcode $mod+$h focus down

# Move windows
bindcode $mod+Shift+$h move left 30 px
bindcode $mod+Shift+$j move down 30 px
bindcode $mod+Shift+$k move up 30 px
bindcode $mod+Shift+$l move right 30 px
bindcode $mod+$period split h
bindcode $mod+$comma split v

# fullscreen
bindcode --no-repeat $mod+$f fullscreen toggle

# Toggle window layout
bindcode --no-repeat $mod+$r layout toggle split

# Change focus
bindcode --no-repeat $mod+$space focus mode_toggle
bindcode --no-repeat $mod+$a focus parent
bindcode --no-repeat $mod+$c focus child

# Change workspace
bindcode --no-repeat $mod+$1 workspace 1
bindcode --no-repeat $mod+$2 workspace 2
bindcode --no-repeat $mod+$3 workspace 3
bindcode --no-repeat $mod+$4 workspace 4
bindcode --no-repeat $mod+$5 workspace 5
bindcode --no-repeat $mod+$6 workspace 6
bindcode --no-repeat $mod+$7 workspace 7
bindcode --no-repeat $mod+$8 workspace 8
bindcode --no-repeat $mod+$9 workspace 9

# Move to other workspace
bindcode --no-repeat $mod+Shift+$1 move container to workspace 1; workspace 1
bindcode --no-repeat $mod+Shift+$2 move container to workspace 2; workspace 2
bindcode --no-repeat $mod+Shift+$3 move container to workspace 3; workspace 3
bindcode --no-repeat $mod+Shift+$4 move container to workspace 4; workspace 4
bindcode --no-repeat $mod+Shift+$5 move container to workspace 5; workspace 5
bindcode --no-repeat $mod+Shift+$6 move container to workspace 6; workspace 6
bindcode --no-repeat $mod+Shift+$7 move container to workspace 7; workspace 7
bindcode --no-repeat $mod+Shift+$8 move container to workspace 8; workspace 8
bindcode --no-repeat $mod+Shift+$9 move container to workspace 9; workspace 9

# Resize window
bindcode $mod+$i resize grow height 10 px or 10 ppt;
bindcode $mod+$u resize shrink height 10 px or 10 ppt;
bindcode $mod+$o resize grow width 10 px or 10 ppt;
bindcode $mod+$y resize shrink width 10 px or 10 ppt;
bindcode $mod+Shift+$i resize grow height 30 px or 30 ppt;
bindcode $mod+Shift+$u resize shrink height 30 px or 30 ppt;
bindcode $mod+Shift+$o resize grow width 30 px or 30 ppt;
bindcode $mod+Shift+$y resize shrink width 30 px or 30 ppt;

# Toggle flaoting
bindcode --no-repeat $mod+Shift+$space exec --no-startup-id \
					 swaymsg 'floating toggle' && \
					 (FLOAT_FILE="${XDG_CONFIG_HOME}/sway/conf.d/float.conf" && \
					 window=$(swaymsg -t get_tree | \
					 jq -r '..|try select(.focused == true)') && \
					 floating=$(printf "${window}" | \
					 jq -r '.floating') && \
					 app_id=$(printf "${window}" | \
					 jq -r '.app_id') && \
					 command='for_window [app_id="'"${app_id}"'"] floating enable' && \
					 test "${floating}" = 'user_on' && \
					 (printf '%s\n' "${command}" >> "${FLOAT_FILE}") || \
					 (grep -Fvs "${command}" "${FLOAT_FILE}" > "${FLOAT_FILE}.tmp" || \
					 true && mv "${FLOAT_FILE}.tmp" "${FLOAT_FILE}")) && \
					 swaymsg 'reload'


# Kill window
bindcode --no-repeat $mod+$q exec --no-startup-id \
					 swaymsg -t get_tree | \
					 jq -r '..|try select(.focused == true)|.app_id//.window_properties.[]' | \
					 grep -iqf - "${XDG_DATA_HOME}/i3/persist" && \
					 notify-send 'Sway' 'Persist on' || \
					 swaymsg 'kill'


# Reload config
bindcode --no-repeat $mod+Shift+$r reload
