for_window [app_id="blueman-manager"] floating enable
for_window [app_id="org.pulseaudio.pavucontrol"] floating enable
for_window [app_id="cobalt"] floating enable
for_window [app_id="null"] floating enable
