# Notification
bindcode $mod+$escape {
	exec --no-startup-id dunstctl close
} 

# Player
bindsym XF86AudioPlay {
	exec --no-startup-id playerctl play && notify-send --hint="string:x-dunst-stack-tag:player" --icon='mediaplayer-app-symbolic' "Player: play"
} 
bindsym XF86AudioPause {
	exec --no-startup-id playerctl pause --all-players && notify-send --hint="string:x-dunst-stack-tag:player" --icon='mediaplayer-app-symbolic' "Player: pause"
} 
bindsym XF86AudioNext {
	exec --no-startup-id playerctl next && notify-send --hint="string:x-dunst-stack-tag:player" --icon='mediaplayer-app-symbolic' "Player: next"
} 
bindsym XF86AudioPrev {
	exec --no-startup-id playerctl previous && notify-send --hint="string:x-dunst-stack-tag:player" --icon='mediaplayer-app-symbolic' "Player: previous"
} 

# Audio
bindcode $mod+$f1 {
	# exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ -1% && volume="$(pamixer --get-volume)" && notify-send --hint="string:x-dunst-stack-tag:volume" --hint="int:value:${volume}" --icon='audio-speakers-symbolic' "Volume: ${volume}%"
	exec --no-startup-id pamixer --decrease 1 && volume="$(pamixer --get-volume)" && notify-send --hint="string:x-dunst-stack-tag:volume" --hint="int:value:${volume}" --icon='audio-speakers-symbolic' "Volume: ${volume}%"
}
bindcode $mod+$f2 {
	# exec --no-startup-id pactl set-sink-volume @DEFAULT_SINK@ +1% && volume="$(pamixer --get-volume)" && notify-send --hint="string:x-dunst-stack-tag:volume" --hint="int:value:${volume}" --icon='audio-speakers-symbolic' "Volume: ${volume}%"
	exec --no-startup-id pamixer --increase 1 && volume="$(pamixer --get-volume)" && notify-send --hint="string:x-dunst-stack-tag:volume" --hint="int:value:${volume}" --icon='audio-speakers-symbolic' "Volume: ${volume}%"
}
bindcode $mod+$f3 {
	exec --no-startup-id pamixer --toggle-mute && notify-send --hint="string:x-dunst-stack-tag:speaker" --icon='audio-speakers-symbolic' "Speaker: $(pamixer --get-volume-human)"
}
bindcode $mod+$f4 {
	exec --no-startup-id pamixer --toggle-mute --default-source && notify-send --hint="string:x-dunst-stack-tag:microphone" --icon='audio-input-microphone-symbolic' "Microphone: $(pamixer --default-source --get-volume-human)"
}
