hide_edge_borders both
default_floating_border pixel
default_border pixel
focus_follows_mouse no
focus_wrapping no
font pango:Noto Sans 10
floating_modifier $mod
focus_on_window_activation urgent

for_window [all] border pixel

for_window [app_id="terminal_scratchpad"] move scratchpad
for_window [app_id="terminal_scratchpad"] scratchpad show
for_window [app_id="terminal_scratchpad"] resize set 75 ppt
for_window [app_id="terminal_scratchpad"] move position center
