## Cursor Control
set $mode_cursor Cursor Control
bindcode --no-repeat $mod+Control+$m mode "$mode_cursor"

mode "$mode_cursor" {
    bindcode $h seat - cursor move -15 0
    bindcode $j seat - cursor move 0 15
    bindcode $k seat - cursor move 0 -15
    bindcode $l seat - cursor move 15 0

    bindcode Shift+$h seat - cursor move -50 0
    bindcode Shift+$j seat - cursor move 0 50
    bindcode Shift+$k seat - cursor move 0 -50
    bindcode Shift+$l seat - cursor move 50 0

    bindcode --no-repeat $space seat - cursor press button1
    bindcode --no-repeat $enter seat - cursor press button2

    bindcode --no-repeat $escape mode "default"
}

## System
set $mode_system (L)ock, (S)uspend, (H)ibernate, (E)xit, (R)eboot, (P)oweroff
bindcode --no-repeat $mod+Shift+$e mode "$mode_system"

mode "$mode_system" {
    bindcode --no-repeat $e exec --no-startup-id swaymsg exit
    bindcode --no-repeat $l exec --no-startup-id swaylock, mode "default"
    bindcode --no-repeat $s exec --no-startup-id systemctl suspend -i, mode "default"
    bindcode --no-repeat $h exec --no-startup-id systemctl hibernate -i, mode "default"
    bindcode --no-repeat $r exec --no-startup-id systemctl reboot -i, mode "default"
    bindcode --no-repeat $p exec --no-startup-id systemctl poweroff -i, mode "default"

    bindcode --no-repeat $escape mode "default"
}

## Force Quit
set $mode_quit Quit: (Y)es/(N)o?
bindcode --no-repeat $mod+Shift+$q mode "$mode_quit"

mode "$mode_quit" {
    bindcode --no-repeat $y kill, mode "default"
    bindcode --no-repeat $n mode "default"

    bindcode --no-repeat $escape mode "default"
}

## Miniplayer
set $mode_miniplayer Miniplayer: 0, 1, 2, 3
bindcode --no-repeat $mod+Shift+$f2 mode "$mode_miniplayer"

mode "$mode_miniplayer" {
    bindcode --no-repeat $0 floating disable; sticky disable; mode "default"
    bindcode --no-repeat $1 floating enable; resize set width 640 height 360; move position 1280px 720px; sticky enable; mode "default"
    bindcode --no-repeat $2 floating enable; resize set width 848 height 480; move position 1056px 594px; sticky enable; mode "default"
    bindcode --no-repeat $3 floating enable; resize set width 960 height 540; move position 960px 540px; sticky enable; mode "default"

    bindcode --no-repeat $escape mode "default"
}

## Kill Window
set $mode_kill Kill Window
bindcode --no-repeat $mod+Shift+$x mode "$mode_kill"

mode "$mode_kill" {
	 bindsym --whole-window button1 kill, mode "default"

	 bindcode --no-repeat $escape mode "default"
}
