#!/bin/sh

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
aliasrc="${XDG_CONFIG_HOME}"/shell/aliasrc

# Shortcut
alias \
  balias='[ -f $aliasrc ] && $EDITOR $aliasrc && . $aliasrc' \
	rm='f(){ echo use del!; }; f' \
	n='/usr/bin/newsboat' \
  m='/usr/bin/neomutt' \
  mutt='/usr/bin/neomutt' \
  v='/usr/bin/nvim' \
  vim='/usr/bin/nvim' \
  copy='/usr/bin/xclip -selection clipboard' \
  myip='/usr/bin/curl -L https://ipinfo.io/ip' \
  del='/usr/bin/trash-put' \
  cpu='/usr/bin/cpupower frequency-info' \
  powersave='sudo /usr/bin/cpupower frequency-set -g powersave' \
  performance='sudo /usr/bin/cpupower frequency-set -g performance' \
  ondemand='sudo /usr/bin/cpupower frequency-set -g ondemand' \
  conservative='sudo /usr/bin/cpupower frequency-set -g conservative' \
  schedutil='sudo /usr/bin/cpupower frequency-set -g schedutil' \
	freq800='sudo /usr/bin/cpupower frequency-set -u 800MHz' \
	freq1200='sudo /usr/bin/cpupower frequency-set -u 1200MHz' \
	freq1600='sudo /usr/bin/cpupower frequency-set -u 1600MHz' \
	freq1900='sudo /usr/bin/cpupower frequency-set -u 1900MHz' \
	freq2700='sudo /usr/bin/cpupower frequency-set -u 2700MHz' \
	xo='f(){ /usr/bin/nohup /usr/bin/xdg-open "$@" >/dev/null 2>&1 & }; f' \
	nh='f(){ /usr/bin/nohup "$@" >/dev/null 2>&1 & }; f' \
  mkd='/usr/bin/mkdir -pv' \
	e='/usr/bin/ranger' \
	mycc='/usr/bin/c99 -Wall -g -o binary' \
	t='tmux attach' \
	todo='$EDITOR ~/doc/TODO'

# Fix
alias \
  ssh='TERM=''xterm-256color'' ssh' \
	mbsync='/usr/bin/mbsync -c "$XDG_CONFIG_HOME"/isync/mbsyncrc'

# System
alias \
  ls='/bin/ls --color=auto --group-directories-first' \
  la='ls -A' \
  l='ls -alh' \
  ll='ls -alhF' \
  grep='/usr/bin/grep --color=auto' \
  diff='/usr/bin/diff --color=auto' \
	free='/usr/bin/free -h'

# Git
alias \
  gits='/usr/bin/git status' \
  g='/usr/bin/git status' \
  gitl='/usr/bin/git log' \
  gitch='/usr/bin/git checkout' \
  gitb='/usr/bin/git branch' \
  gitd='/usr/bin/git diff' \
	gitc='/usr/bin/git commit' \
	gita='/usr/bin/git add' \
	gitds='/usr/bin/git diff --staged'

# Docker
alias \
  dkps='/usr/bin/docker ps -a' \
  dkr='/usr/bin/docker run' \
  dks='/usr/bin/docker stop' \
  dkrm='/usr/bin/docker rm' \
  dkrmi='/usr/bin/docker rmi' \
  dkcu='/usr/bin/docker-compose up' \
  dkcd='/usr/bin/docker-compose down' \
  dkcr='/usr/bin/docker-compose restart'

# Pacman
alias \
	paci='f(){ sudo /usr/bin/pacman -S "$@" && /usr/bin/notify-send "Pacman" "Package(s) installed"; }; f' \
	pacr='sudo /usr/bin/pacman -Rns' \
	pacs='/usr/bin/pacman -Ss' \
	pacw='sudo /usr/bin/pacman -Syuw --noconfirm; /usr/bin/flatpak update --assumeyes --no-deploy; /usr/bin/notify-send "Package Manager" "Updates downloaded"' \
	pacu='sudo /usr/bin/pacman -Syu --noconfirm; /usr/bin/flatpak update --assumeyes; /usr/bin/notify-send "Package Manager" "System updated"'
