#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  A collection of aliases

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"
ALIASRC="${XDG_CONFIG_HOME}"/shell/aliasrc

# Shortcut
alias \
  balias="[ -f ${ALIASRC} ] && ${EDITOR} ${ALIASRC} && . ${ALIASRC}" \
	rm='f(){ echo use del!; }; f' \
	n='newsboat' \
  m='neomutt' \
  mutt='neomutt' \
  v='nvim' \
  vim='nvim' \
  copy='xclip -selection clipboard' \
  myip='curl -L https://ipinfo.io/ip' \
  del='trash-put' \
  cpu='cpupower frequency-info' \
  powersave='sudo cpupower frequency-set -g powersave' \
  performance='sudo cpupower frequency-set -g performance' \
  ondemand='sudo cpupower frequency-set -g ondemand' \
  conservative='sudo cpupower frequency-set -g conservative' \
  schedutil='sudo cpupower frequency-set -g schedutil' \
	freq400='sudo cpupower frequency-set -u 400MHz' \
	freq800='sudo cpupower frequency-set -u 800MHz' \
	freq1200='sudo cpupower frequency-set -u 1200MHz' \
	freq1400='sudo cpupower frequency-set -u 1400MHz' \
	freq1600='sudo cpupower frequency-set -u 1600MHz' \
	freq1900='sudo cpupower frequency-set -u 1900MHz' \
	freq6000='sudo cpupower frequency-set -u 2700MHz' \
	xo='f(){ nohup xdg-open "${@}" >/dev/null 2>&1 & }; f' \
	nh='f(){ nohup "${@}" >/dev/null 2>&1 & }; f' \
	mycc='c99 -Wall -g -o binary' \
	t='tmux attach' \
	todo="${EDITOR} ${XDG_DOCUMENTS_DIR}/TODO" \
	alarm='f(){ termdown "${@}" && yes "Alarm" | espeak; }; f'

# Fix
alias \
  ssh='TERM=''xterm-256color'' ssh' \
	mbsync="mbsync -c ${XDG_CONFIG_HOME}/isync/mbsyncrc"

# System
alias \
  ls='/bin/ls --color=auto --group-directories-first' \
  la='ls -A' \
  l='ls -alh' \
  ll='ls -alhF' \
  grep='grep --color=auto' \
  diff='diff --color=auto' \
	free='free -h'

# Git
alias \
  gits='git status' \
  g='git status' \
  gitl='git log' \
  gitch='git checkout' \
  gitb='git branch' \
  gitd='git diff' \
	gitc='git commit' \
	gita='git add' \
	gitds='git diff --staged'

# Docker
alias \
  dkps='docker ps -a' \
  dkr='docker run' \
  dks='docker stop' \
  dkrm='docker rm' \
  dkrmi='docker rmi' \
  dkcu='docker-compose up' \
  dkcd='docker-compose down' \
  dkcr='docker-compose restart'

# Pacman
alias \
	paci='f(){ sudo pacman -S "${@}" && notify-send "Pacman" "Package(s) installed"; }; f' \
	pacr='sudo pacman -Rns' \
	pacs='pacman -Ss' \
	pacw='sudo pacman -Syuw --noconfirm; flatpak update --assumeyes --no-deploy; notify-send "Package Manager" "Updates downloaded"' \
	pacu='sudo pacman -Syu --noconfirm; flatpak update --assumeyes; notify-send "Package Manager" "System updated"'
