#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  Shell profile

assign_env(){
	# XDG Session
	export XDG_SESSION_TYPE='wayland'

	# XDG Directory
	export XDG_CONFIG_HOME="${HOME}/.config"
	export XDG_CACHE_HOME="${HOME}/.cache"
	export XDG_STATE_HOME="${HOME}/.local/state"
	export XDG_DATA_HOME="${HOME}/.local/share"
	export XDG_DATA_BIN="${HOME}/.local/bin"
	export XDG_DATA_DIRS="${HOME}/.local/share${XDG_DATA_DIRS:+:${XDG_DATA_DIRS}}"
	export XDG_CONFIG_DIRS="${HOME}/.config${XDG_CONFIG_DIRS:+:${XDG_CONFIG_DIRS}}"

	# Programs
	export EDITOR='nvim'
	export VISUAL='nvim'
	export PAGER='less'
	export TERMINAL='alacritty'
	export TERMINAL_TMUX='alacritty --command tmux new-session -A'
	export TERMINAL_SCRATCHPAD='alacritty --class terminal_scratchpad --command tmux new-session -A'
	export EMAIL='alacritty --option window.opacity=1.0 --command neomutt'
	export RSSFEED="alacritty --option window.opacity=1.0 --command newsboat --url-file ${XDG_DATA_HOME}/newsboat/urls"
	export FILEMANAGER='alacritty --command lf'
	export BROWSER='io.github.ungoogled_software.ungoogled_chromium'
	export PRIVATE_BROWSER='io.github.ungoogled_software.ungoogled_chromium --incognito'
	export TERMINAL_BROWSER='w3m'
	export SCREENSHOT='flameshot gui'
	export PDFREADER='zathura'
	export FZF_DEFAULT_COMMAND='fd .'
	export FZF_CTRL_T_COMMAND="${FZF_DEFAULT_COMMAND}"
	export FZF_ALT_C_COMMAND='fd --type d .'
	export ZDOTDIR="${XDG_CONFIG_HOME}/zsh"

	#	Fixes
	export DOCKER_HOST="unix://${XDG_RUNTIME_DIR}/podman/podman.sock" 
	# export GTK_IM_MODULE='fcitx'
	# export QT_IM_MODULE='fcitx'
	# export SDL_IM_MODULE='fcitx'
	# export XMODIFIERS='@im=fcitx'

	# Home directory clean up
	export XAUTHORITY="${XDG_RUNTIME_DIR}/Xauthority"
	export HISTFILE="${XDG_DATA_HOME}/shell/history"
	export BASH_COMPLETION_USER_FILE="${XDG_DATA_HOME}/bash/bash_completion"
	export LESSKEY="${XDG_CONFIG_HOME}/less/lesskey"
	export LESSHISTFILE="${XDG_CACHE_HOME}/less/history"
	export LESSHISTFILE='-'
	export GRADLE_USER_HOME="${XDG_DATA_HOME}/gradle"
	export ANDROID_PREFS_ROOT="${XDG_CONFIG_HOME}/android"
	export ANDROID_EMULATOR_HOME="${XDG_DATA_HOME}/android/emulator"
	export IPYTHONDIR="${XDG_CONFIG_HOME}/jupyter"
	export JUPYTER_CONFIG_DIR="${XDG_CONFIG_HOME}/jupyter"
	export MOZ_GTK_TITLEBAR_DECORATION='client'
	export PASSWORD_STORE_DIR="${XDG_DATA_HOME}/password-store"
	export PUB_CACHE="${XDG_CACHE_HOME}/pub"
	export GOPATH="${XDG_DATA_HOME}/go"
	export CALCHISTFILE="${XDG_CACHE_HOME}/calc_history"
	export VSCODE_PORTABLE="${XDG_CONFIG_HOME}/vscode"
	export GTK2_RC_FILES="${XDG_CONFIG_HOME}/gtk-2.0/gtkrc:${XDG_CONFIG_HOME}/gtk-2.0/gtkrc.mine"

	# PATH
	export PATH="${XDG_DATA_BIN}${PATH:+:${PATH}}"
}

set_umask(){
	umask 0022
}

create_directories(){
	mkdir -p "${XDG_DATA_HOME}/gnupg"
	mkdir -p "${XDG_DATA_HOME}/shell"
}

start_x11(){
	printf '%s' '==========' "$(date)" '==========' >> "${XDG_CACHE_HOME}/xorg.log"

	exec startx "${XDG_CONFIG_HOME}/x11/xinitrc" -- -keeptty >> "${XDG_CACHE_HOME}/xorg.log" 2>&1
}

start_wayland(){
	if [ -n "${WAYLAND_DISPLAY}" ]; then
		return
	fi

	printf '%s' '==========' "$(date)" '==========' >> "${XDG_CACHE_HOME}/sway.log"

	exec sway >> "${XDG_CACHE_HOME}/sway.log" 2>&1
}

start_desktop(){
	if [ "${XDG_VTNR}" -ne 1 ]; then
		return
	fi

	if [ -n "${DISPLAY}" ]; then
		return
	fi

	case "${XDG_SESSION_TYPE}" in
		'x11') start_x11;;
		'wayland') start_wayland;;
		*) return;;
	esac
}

main(){
	assign_env
	set_umask
	create_directories
	start_desktop
}

main "${@}"
