# Defaults
if [ -d /etc/X11/xinit/xinitrc.d ]; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Xresources
if [ -f "$XDG_CONFIG_HOME"/x11/xresources ]; then
	xrdb -merge "$XDG_CONFIG_HOME"/x11/xresources
fi

pgrep autorandr || autorandr -c

# DE/WM
pgrep i3 || exec i3
