#!/bin/sh

# Author:       Action <dev@action-server.com>
# License:      GNU GPLv3
# Description:  X11 init file

source_xinit_default(){
	file="${1}"

	if [ ! -x "${file}" ]; then
		return
	fi

	. "${file}"
}

source_all_xinit_defaults(){
	if [ ! -d /etc/X11/xinit/xinitrc.d ]; then
		return
	fi

	for file in /etc/X11/xinit/xinitrc.d/?*.sh; do
		source_xinit_default "${file}"
	done
}

run_xrdb(){
	if [ ! -f "${XDG_CONFIG_HOME}/x11/xresources" ]; then
		return
	fi

	xrdb -merge "${XDG_CONFIG_HOME}/x11/xresources"
}

run_programs(){
	autorandr -c

	sxhkd -m 1 &

	exec i3
}

main(){
	source_all_xinit_defaults
	run_xrdb
	run_programs
}

main "${@}"
